data:
  coin_id: "bitcoin"
  vs_currency: "usd"
  days: "365"

preprocessing:
  window_size: 60

training:
  epochs: 10
  batch_size: 32
  validation_split: 0.2
  save_path: "models/saved_model.keras"
